<?php

namespace Stinger\Contact;

use Illuminate\Support\ServiceProvider;

class ContactServiceProvider extends ServiceProvider
{

    public function boot()
    {
        /*Inicializa Rotas do Pacote de Contact(Email)*/
        $this->loadRoutesFrom(__DIR__."/routes/web.php");

        /*Inicializa Views do Pacote de Contact(Email)*/
        $this->loadViewsFrom(__DIR__."/views", 'contact');

        /*Inicializa Migrations do Pacote de Contact(Email)*/
        $this->loadMigrationsFrom(__DIR__."/database/migrations");

        /**
         * Inicializa Configurações do Pacote de Contact(Email)
         * */
        $this->mergeConfigFrom(__DIR__."/config/contact.php", 'contact');
        /*Publicando Registro de configuração dentro do Projeto*/
        $this->publishes(
            [__DIR__."/config/contact.php" => config_path('contact.php')]
        );
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
